# Generated by Django 3.0.3 on 2021-02-02 22:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amci', models.CharField(default='', max_length=8, unique=True)),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenoms', models.CharField(default='', max_length=50)),
                ('mail', models.EmailField(default='', max_length=100)),
                ('date_nais', models.DateField()),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('annee_bourse', models.IntegerField(default=2020)),
                ('instagram', models.CharField(blank=True, default='', max_length=250)),
                ('facebook', models.CharField(blank=True, default='', max_length=250)),
                ('twitter', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
    ]
