# Generated by Django 3.0.3 on 2021-02-02 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('pdf', models.FileField(upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6, verbose_name=9999)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BoardMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary')], default='Super Admin', max_length=15)),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenoms', models.CharField(default='', max_length=50)),
                ('mail', models.EmailField(default='', max_length=100)),
                ('date_nais', models.DateField()),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
